/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Button: typeof import('antd').Button
  const Card: typeof import('antd').Card
  const Form: typeof import('antd').Form
  const Input: typeof import('antd').Input
  const Layout: typeof import('antd').Layout
  const Menu: typeof import('antd').Menu
  const Modal: typeof import('antd').Modal
  const Popconfirm: typeof import('antd').Popconfirm
  const Popover: typeof import('antd').Popover
  const Space: typeof import('antd').Space
  const Table: typeof import('antd').Table
  const Tooltip: typeof import('antd').Tooltip
  const message: typeof import('antd').message
  const theme: typeof import('antd').theme
}
