/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Button: typeof import('antd').Button
  const Card: typeof import('antd').Card
  const Divider: typeof import('antd').Divider
  const Input: typeof import('antd').Input
  const Space: typeof import('antd').Space
  const Statistic: typeof import('antd').Statistic
  const Tag: typeof import('antd').Tag
}
