/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ADMIN_PATH: typeof import('../router/constant').ADMIN_PATH
  const ErrorBoundary: typeof import('../components/index').ErrorBoundary
  const HOME_PATH: typeof import('../router/constant').HOME_PATH
  const LOGIN_PATH: typeof import('../router/constant').LOGIN_PATH
  const LazyImport: typeof import('../components/index').LazyImport
  const Loading: typeof import('../components/index').Loading
  const MANAGE_PATH: typeof import('../router/constant').MANAGE_PATH
  const NotFound: typeof import('../components/index').NotFound
  const UserProfileDropdown: typeof import('../components/index').UserProfileDropdown
  const cancel: typeof import('../services/index').cancel
  const findActiveMenu: typeof import('../utils/menu.util').findActiveMenu
  const formatDate: typeof import('../utils/date.util').formatDate
  const getAntdThemeTokens: typeof import('../store/index').getAntdThemeTokens
  const persistor: typeof import('../store/index').persistor
  const request: typeof import('../services/index').request
  const router: typeof import('../router/index').default
  const routesToAntdMenu: typeof import('../utils/menu.util').routesToAntdMenu
  const setThemeVariables: typeof import('../store/index').setThemeVariables
  const store: typeof import('../store/index').default
  const tableConfig: typeof import('../config/antd/table').tableConfig
  const useActiveMenu: typeof import('../hooks/index').useActiveMenu
  const useAppDispatch: typeof import('../store/index').useAppDispatch
  const useAppSelector: typeof import('../store/index').useAppSelector
  const useRequest: typeof import('../utils/axios/index').useRequest
}
// for type re-export
declare global {
  // @ts-ignore
  export type { RootState, AppDispatch } from '../store/index'
  import('../store/index')
  // @ts-ignore
  export type { MenuItem } from '../utils/menu.util'
  import('../utils/menu.util')
  // @ts-ignore
  export type { CustomAxiosRequestConfig, ApiResponse } from '../utils/axios/index'
  import('../utils/axios/index')
}
